- hosts: servers
  user: "{{ lookup('env','OS_USER_NAME') }}"
  sudo: no
  tasks:
  - name: verify phpunit installation
    command: which phpunit
    register: verify
    ignore_errors: true
    # failed_when: false # never fails
    changed_when: verify.rc != 0
  - name: Download phpunit.phar
    when: verify | failed
    command: wget https://phar.phpunit.de/phpunit.phar
  - name: Add x permission to phpunit
    when: verify | failed
    command: chmod +x phpunit.phar
  - name: Move to bin
    when: verify | failed
    command: mv phpunit.phar /usr/local/bin/phpunit
    sudo: yes
  - name: Remove from bin
    command: rm -f /usr/local/bin/phpunit
    sudo: yes
