- hosts: servers
  user: "{{ lookup('env','OS_USER_NAME') }}"
  sudo: no
  roles:
    - system
    - php
    - ruby
    - node
    - java
    - scala
    - python3
    - git

#    - mysql
#    - postgresql
