- hosts: all
  user: "{{ lookup('env','OS_USER_NAME') }}"
  sudo: no
  roles:
    - system
    - git
    - clang
    - gcc
    - go
    - gpp
    - gradle
    - groovy
    - haskell
    - java
    - mono
    - node
    - ocaml
    - perl
    - php
    - python3
    - ruby
    - scala

#    - mysql
#    - postgresql
