- hosts: all
  sudo: no
  roles:
    - node
  tasks:
  - name: pong
    command: echo pong
    changed_when: false
  - name: magic--- ansible connection type
    debug:
      var: ansible_connection
  - name: magic--- ansible ssh login user
    debug:
      var: ansible_ssh_user
  - name: magic--- ansible login user
    debug:
      var: ansible_user_id
