---
- name: Add repository for ruby 2.2
  sudo: yes
  apt_repository:
    repo: "ppa:brightbox/ruby-ng"
  tags: [ "ruby", "ruby-lang" ]
- name: Upgrade packages
  sudo: yes
  apt: update_cache=yes upgrade=yes
  tags: [ "ruby", "ruby-lang" ]
- name: Install ruby
  sudo: yes
  apt:
    name: "{{ item }}"
  with_items:
    - ruby2.2
    - ruby2.2-dev
  tags: [ "ruby", "ruby-lang" ]
- name: Make symlink to ruby2.2
  sudo: yes
  file:
    path: /usr/bin/ruby
    src: /usr/bin/ruby2.2
    state: link
  tags: [ "ruby", "ruby-lang" ]
- name: Make symlink to gem2.2
  sudo: yes
  file:
    path: /usr/bin/gem
    src: /usr/bin/gem2.2
    state: link
  tags: [ "ruby", "ruby-lang", "gem" ]
- name: gem update
  sudo: yes
  gem:
    name: system
  tags: [ "ruby", "ruby-lang", "gem" ]
- name: export Path
  lineinfile:
    dest: ~/.profile
    line: 'export PATH="$HOME/.gem/ruby/2.2.0/bin:$PATH"'
    regexp: ".gem/ruby/2.2.0/bin"
  tags: [ "ruby", "ruby-lang", "gem" ]

