---
- name: Create lib dir
  file: path={{activator_lib_path}} state=directory
  sudo: yes

- name: Clean existing version {{activator_version}} if it exists
  file: path={{activator_lib_path_target}} state=absent
  sudo: yes

- name: Download activator v{{activator_version}}
  get_url: url={{activator_download_url}}
    dest=/tmp/{{activator_archive_file}}
    force=no
  sudo: yes

- name: Unpack activator
  command: unzip {{activator_archive_file}} chdir=/tmp/ creates={{activator_archive_name}}
  sudo: yes

- name: Change mode
  file: path=/tmp/{{activator_archive_name}}/activator mode=0755
  sudo: yes

- name: Move (by force) activator to lib
  command: mv /tmp/{{activator_archive_name}} {{activator_lib_path_target}} chdir=/tmp/
  sudo: yes

- name: Link activator
  command: ln -sf {{activator_lib_path_target}}/activator {{activator_link_target}}
  sudo: yes

