- name: check groovy installed
  shell: type groovy
  register: verify_groovy
  failed_when: verify_groovy.rc not in [0, 1, 127]
  changed_when: verify_groovy | failed
- name: install groovy binary
  when: verify_groovy | changed
  get_url:
    url: "{{groovy_binary_url}}"
    dest: /tmp/{{groovy_dir_name}}.zip
- name: unarchive groovy binary zip
  sudo: yes
  when: verify_groovy | failed
  unarchive:
    copy: no
    src: /tmp/{{groovy_dir_name}}.zip
    dest: /usr/local/share
    creates: /usr/local/share/{{groovy_dir_name}}
- name: install groovy
  sudo: yes
  file:
    path: /usr/local/bin/{{item}}
    src: /usr/local/share/{{groovy_dir_name}}/bin/{{item}}
    state: link
  with_items:
    - grape
    - groovy
    - groovyc
    - groovyConsole
    - groovydoc
    - groovysh
    - java2groovy
    - startGroovy

