---
  - name: Verify gradle installation
    shell: type gradle
    register: verify_gradle
    failed_when: false # never fails
    changed_when: verify_gradle | failed
  - name: Download gradle {{gradle_version}}
    when: verify_gradle | failed
    get_url:
      dest: "{{ ansible_env.HOME }}/"
      url: https://services.gradle.org/distributions/gradle-{{gradle_version}}-bin.zip
    tags: [gradle]
  - name: Extract gradle
    sudo: yes
    when: verify_gradle | failed
    shell: unzip "{{ ansible_env.HOME }}/gradle-{{gradle_version}}-bin.zip" -d /usr/local/share/
    args:
      creates: /usr/local/share/gradle-{{gradle_version}}
    tags: [gradle]
  - name: Add Gradle executable symlink to path
    sudo: yes
    when: verify_gradle | failed
    file:
      path: /usr/local/bin/gradle
      src: /usr/local/share/gradle-{{gradle_version}}/bin/gradle
      state: link
    tags: [gradle]
