- name: Add repository for php 5.6
  sudo: yes
  apt_repository: repo=ppa:ondrej/php5-5.6
  tags: [ "php" ]
- name: Upgrade packages
  sudo: yes
  apt: update_cache=yes upgrade=yes
  tags: [ "php" ]
- name: Install php packages
  sudo: yes
  apt:
    name: "{{ item }}"
  with_items:
  - php5
  - php5-cli
  - php5-common
  - php5-curl
  - php5-gd
  - php5-json
  - php5-mcrypt
  - php5-mysql
  - php5-pgsql
  - php5-sqlite
  tags: [ "php" ]
- name: install composer
  sudo: yes
  shell: curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/bin --filename=composer
  tags: [ "php" ]
- include: phpunit.yml
