- name: Add repository for php 5.6
  sudo: yes
  apt_repository: repo=ppa:ondrej/php5-5.6
  tags: [ "php" ]
- name: Upgrade packages
  sudo: yes
  apt: update_cache=yes upgrade=yes
  tags: [ "php" ]
- name: Install php packages
  sudo: yes
  apt:
    name: "{{ item }}"
  with_items:
  - php5-cli
  - php5-curl
  - php5-mysql
  - php5-gd
  tags: [ "php" ]
- name: check composer installed
  shell: type composer
  register: verify_composer
  failed_when: verify_composer.rc not in [0, 1, 127]
  changed_when: verify_composer.rc in [1, 127]
  tags: [ "php" ]
- name: install composer
  when: verify_composer | changed
  sudo: yes
  shell: curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/bin --filename=composer
  tags: [ "php" ]
- include: phpunit.yml
