- name: Set fact for version 2.x
  when: version == "2.x"
  set_fact:
    install_prefix: python
  tags: [ "python", "nose" ]
- name: Set fact for version 3.x
  when: version == "3.x"
  set_fact:
    install_prefix: python3
  tags: [ "python", "nose" ]
- name: Install Python{{ version }}
  sudo: yes
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - "{{ install_prefix }}-all-dev"
    - "{{ install_prefix }}-setuptools"
    - "{{ install_prefix }}-pip"
  tags: [ "python", "nose" ]
