- name: Verify node installation
  shell: type node
  register: verify_node
  failed_when: verify_node.rc not in [0, 1, 127]
  changed_when: verify_node.rc in [1, 127]
- name: Download node package
  when: verify_node | changed
  sudo: yes
  shell: curl -sL https://deb.nodesource.com/setup_{{node_version}} | bash -
  args:
    creates: /etc/apt/sources.list.d/nodesource.list
- name: Install NodeJS
  sudo: yes
  apt:
    name: nodejs
- name: Install altjs
  sudo: yes
  npm:
    name: "{{ item.name }}"
    global: "{{ item.global }}"
  with_items:
    - { name: typescript, global: yes }
    - { name: coffee-script, global: yes }
    - { name: babel-cli, global: yes }
- name: Install testing frameworks
  sudo: yes
  npm:
    name: "{{ item.name }}"
    global: "{{ item.global }}"
  with_items:
    - { name: mocha, global: yes }
    - { name: karma, global: yes }
- name: Install build tools
  sudo: yes
  npm:
    name: "{{ item.name }}"
    global: "{{ item.global }}"
  with_items:
    - { name: grunt-cli, global: yes }
    - { name: gulp, global: yes }
    - { name: webpack, global: yes}
