- name: Add repository for git
  sudo: yes
  apt_repository:
    repo: "ppa:git-core/ppa"
  tags: [ "git" ]
- name: Upgrade packages
  sudo: yes
  apt:
    update_cache: yes
    upgrade: safe
  tags: [ "git" ]
- name: Install git
  sudo: yes
  apt:
    name: git
  tags: [ "git" ]
- name: copy private key
  when: private_key_path | default("") != ""
  copy:
    src: "{{private_key_path}}"
    dest: "~/.ssh/id_rsa"
    owner: "{{ansible_user_id}}"
    mode: 0600
  tags: [ "git" ]

