---
scala_version: "2.11.7"
scala_version_name: "scala-{{ scala_version }}"
scala_archive_file: "{{ scala_version_name }}.tgz"
scala_download_url: "http://www.scala-lang.org/files/archive/{{ scala_archive_file }}"

scala_lib_path: "/usr/local/share/scala"
scala_lib_path_target: "{{ scala_lib_path }}/{{ scala_version_name }}"

sbt_version: "0.13.9"
sbt_archive_name: "sbt"
sbt_archive_file: "sbt-{{ sbt_version }}.tgz"
sbt_download_url: "https://dl.bintray.com/sbt/native-packages/sbt/{{ sbt_version }}/{{ sbt_archive_file }}"

sbt_lib_path: "/usr/local/share/sbt"
sbt_lib_path_target: "{{ sbt_lib_path }}/{{ sbt_version }}"

activator_version: "1.3.2"
activator_archive_name: "activator-{{ activator_version }}-minimal"
activator_archive_file: "{{ activator_archive_name }}.zip"
activator_download_url: "http://downloads.typesafe.com/typesafe-activator/{{ activator_version }}/typesafe-activator-{{ activator_version }}-minimal.zip"

activator_lib_path: "/usr/local/share/activator"
activator_lib_path_target: "{{ activator_lib_path }}/{{ activator_version }}"
activator_link_target: "/usr/local/bin"
