- name: Add repository for php 5.5
  apt_repository: repo=ppa:ondrej/php5
  sudo: yes
- name: Upgrade packages
  apt: update_cache=yes upgrade=yes
  sudo: yes

- name: Install php 5.5
  apt: pkg={{item}}
  with_items:
  - php5-cli
  - php5-curl
  - php5-mysql
  - php5-gd
  sudo: yes

- name: check composer installed
  command: test -f /usr/bin/composer
  ignore_errors: true
  register: verify_composer
  failed_when: false
  changed_when: verify_composer | failed
  sudo: no
- name: install composer
  shell: curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/bin
  when: verify_composer | failed
  sudo: yes
- name: move composer.phar to composer
  command: mv /usr/bin/composer.phar /usr/bin/composer
  when: verify_composer | failed
  sudo: yes
- include: phpunit.yml
