- name: Add repository for php 5.5
  apt_repository: repo=ppa:ondrej/php5
- name: Upgrade packages
  apt: update_cache=yes upgrade=yes

- name: Install php 5.5
  apt: pkg={{item}}
  with_items:
  - php5
  - php5-cli
  - php5-curl
  - php5-mysql
  - php5-gd

- name: check composer installed
  command: test -f /usr/bin/composer
  ignore_errors: true
  register: var_composer_installed
  failed_when: false
  changed_when: var_composer_installed.rc != 0
- name: install composer
  shell: curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/bin
  when: var_composer_installed.rc != 0
- name: move composer.phar to composer
  command: mv /usr/bin/composer.phar /usr/bin/composer
  when: var_composer_installed.rc != 0
